- name : Restart VM with souce vmid
  hosts: all
  
  tasks: 
    - name : Restart VM PROXMOX
      proxmox_kvm:
        api_user: root@pam
        api_password: r43QAY$Ypc7d
        api_host: SRVPAPV001
        vmid: 110
        node: SRVPAPV001
        state: restarted