- name : Ajout d'un nouvel hôte
  hosts: all

  tasks: 
    - name: Ajout d'un nouvel hôte
      community.windows.win_dns_record:
        name: "SRVPATEST01"
        type: "A"
        value: "10.0.1.43"
        zone: "chareauto.com"
    - name: Create matching PTR record
      community.windows.win_dns_record:
        name: "43"
        type: "PTR"
        value: "SRVPATEST01.chareauto.com"
        zone: "1.0.10.in-addr.arpa"