- name : Ajout d'un nouvel hôte
  hosts: all

  tasks: 
    - name: Ajout d'un nouvel hôte
      community.windows.win_dns_record:
        name: "SRVPADOCK001"
        type: "A"
        value: "10.0.1.17"
        zone: "chareauto.com"